services:
  redis:
    image: redis:7-alpine
    container_name: taskqueue-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - taskqueue-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskqueue-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - taskqueue-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskqueue-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKERS=4
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: python worker.py
    networks:
      - taskqueue-network
    deploy:
      replicas: 1

volumes:
  redis_data:

networks:
  taskqueue-network:
    driver: bridge

